<template>
  <v-card
    elevation="0"
    class="advertisement d-flex align-center text-center text-sm-left justify-center justify-md-start"
  >
    <div class="w-50 tracking-in-expand mx-sm-10">
      <h1 class="text-white text-h4 text-sm-h3 font-weight-bold">Hot Property Deal!</h1>
      <p class="text-white text-h7 text-sm-h6">
        Discover our latest hot property deal! Don't miss this exclusive opportunity to own a
        stunning home at an unbeatable price. Whether you're looking for your dream home or a smart
        investment, this is your chance. Contact us today to seize this limited-time offer and make
        your real estate dreams come true.
      </p>
      <v-btn variant="outlined" color="white" class="ma-3">See offert</v-btn>
    </div>
  </v-card>
</template>

<style>
.advertisement {
  background-image: linear-gradient(to right, rgba(0, 0, 0, 0.292), rgba(0, 0, 0, 0.7)),
    url('../assets/bgAdvertisement.jpg');
  height: 600px;
  background-size: cover;
  background-position: center;
}

@media (min-width: 992px) {
  .advertisement {
    height: 350px;
  }
}
.tracking-in-expand {
  -webkit-animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1) both;
  animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-11-9 9:46:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
</style>
