<template>
  <v-card elevation="0" class="header d-flex justify-center align-center">
    <div class="text-center w-50 tracking-in-expand">
      <h1 class="text-white text-h4 text-sm-h3 font-weight-bold">Discover Your Dream Home Today</h1>
      <p class="text-white text-h7 text-sm-h6">
        Explore a world of possibilities in the real estate market. Find the perfect property that
        suits your lifestyle and aspirations with our expert guidance.
      </p>
      <v-btn variant="outlined" color="white" class="ma-3">Contact Us</v-btn>
    </div>
  </v-card>
</template>

<style>
.header {
  background-image: linear-gradient(to right, rgba(0, 0, 0, 0.162), rgba(0, 0, 0, 0.7)),
    url('../assets/header.jpg');
  height: 600px;
  background-size: cover;
  background-position: center;
}
.tracking-in-expand {
  -webkit-animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1) both;
  animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-11-9 9:46:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
</style>
